### ISSUE TITLE
Styling issue with Trained Spotter radio buttons

### ISSUE THREAD

**Issue by scrow** [scrow/wx4akq-offline-tools#1]
Buttons appear to "wiggle" when clicked/toggled in Internet Explorer 9.  May need to see about setting a default border in the CSS?

**Comment by scrow** [comment]
Screen shot:

![buttonwiggle](https://cloud.githubusercontent.com/assets/1059209/10309853/cf9ef06e-6c0c-11e5-9b61-718eeddc8e75.PNG)

Same behavior with the Training Report buttons.

**Comment by scrow** [comment]
Can we disable the orange border altogether on the individual radio buttons?

**Comment by rbarden** [comment]
I believe I have a fix. It will get rid of borders when the radio button is clicked. Waiting on the Windows VM to do its update thing which could take a while and then I'll test it out.

**Comment by scrow** [comment]
Fixed.
